### ISSUE TITLE
Meta v1.2 Scope out needs to submit package to cran

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#186]
## Goal
Installing from CRAN is easier for a lot of users. We should scope out what we would need to do to get this package on cran. 

## Tasks
- [ ] separate github actions for `R CMD check` with and without --as-cran
- [ ] move `cmdstanr` to suggests
- [ ] write `skip_on_cran()` functions for any tests that use cmdstan, similar to in `primarycensoreddist()` https://github.com/epinowcast/primarycensoreddist/blob/d293504f4107af6f68654842b551b5b26856ce2d/tests/testthat/test-stan-primary_censored_ode.R#L1
- [ ] add examples to every function, or if an internal function than remove `export` and tag with `@noRd`
- [ ] make title capital letters

**Comment by dylanhmorris** [comment]
I am not convinced this should be a particularly high priority, particularly since we currently have a non-CRAN package (`cmdstanr`) as an essential dependency (see my comments in #188).
