### ISSUE TITLE
Meta: v0.1

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#6]
## Goal
Tracking steps to a MVP modeling package. The goal is a minimum package that we can share with internal and external partners wanting to run the model on their own data and/or set up production pipelines.

## Features
- [X] R package infrastructure #1 
- [X] CI set up for testing suite
- [X] Minimum pre-processing and model fitting wrapper in a "getting started" vignette #5 
- [X] Validate input data #4 
- [X] Standardize and stabilize `wwinference()` output structure 
- [X] Port over existing model tests
- [X] Add new tests for functions #27
- [X] Make sure every exported function has complete documentation 
- [X] #3 
- [X] Minimum post-processing to make it easy for the user to access: posterior draws of global $R(t)$, site-level $R(t)$, hospital admissions calibrated and forecasted, wastewater concentrations calibrated and forecasted  #5 
- [X] Updated README #7 
- [X] Updated model definition #7
